spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#eureka:
#  client:
#    defaultZone: http://localhost:8761/eureka/
#  instance:
#    lease-renewal-interval-in-seconds: 3
#    lease-expiration-duration-in-seconds: 5